In [4]:
import torch
import numpy as np

In [5]:
x_np = torch.from_numpy(np.array([[1,2],[3,4]]))

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
shape=(1,2,)

rand_tensor=torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


In [8]:
rand_tensor

tensor([[0.5488, 0.1694]])

In [9]:
ones_tensor

tensor([[1., 1.]])

In [10]:
zeros_tensor

tensor([[0., 0.]])

In [13]:
rand_tensor.shape

torch.Size([1, 2])

In [14]:
rand_tensor.device

device(type='cpu')

In [15]:
rand_tensor=rand_tensor.cuda()

In [16]:
rand_tensor.device

device(type='cuda', index=0)

In [19]:
if torch.cuda.is_available():
    tensor=tensor.to("cuda")

In [18]:
tensor=rand_tensor

In [20]:
tensor=torch.ones(4,4)

In [21]:
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [22]:
tensor[...,-1]

tensor([1., 1., 1., 1.])

In [23]:
y1 = tensor.matmul(tensor.T)

In [24]:
y1

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [25]:
agg=tensor.sum()
agg

tensor(16.)

In [26]:
agg.item()

16.0

In [27]:
# in-place 연산
# 함수 뒤에 _ 붙음
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [28]:
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [29]:
tensor.numpy()

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]], dtype=float32)

In [30]:
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

AttributeError: 'Tensor' object has no attribute 'numpy_'