In [1]:
import torch
import numpy as np


In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
t.ndim

1

In [4]:
t.shape

(7,)

In [10]:
t = np.random.rand(4,3)
t

array([[0.39379087, 0.69399238, 0.91705274],
       [0.98606043, 0.84720044, 0.9965688 ],
       [0.00641627, 0.54425032, 0.68122553],
       [0.63076252, 0.63987706, 0.91004573]])

In [11]:
t.ndim

2

In [12]:
t.shape

(4, 3)

In [13]:
t = torch.FloatTensor([x for x in range(7)])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

### Broadcasting
- 자동으로 size 맞춰서 계산

In [14]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

In [15]:
m1

tensor([[3., 3.]])

In [16]:
m2

tensor([[2., 2.]])

In [17]:
m1+m2

tensor([[5., 5.]])

In [18]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m1+m2

tensor([[4., 5.]])

In [19]:
# 2x1 vector + 1x2 vector

m1 = torch.Tensor([[1,2]])
m2 = torch.Tensor([[3],[4]])
m1+m2

tensor([[4., 5.],
        [5., 6.]])

In [20]:
# broadcasting은 자동으로 계산되기 때문에 사용할 때 주의해야함

In [21]:
# integer type에서는 mean을 구할 수 없음
t = torch.LongTensor([1,2])
t

tensor([1, 2])

In [22]:
t.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

### View (Reshape)
- numpy에서는 reshape
- pytorch tensor에서는 view

### Squeeze
- 해당 dimension의 element 수가 1일 때 그 dimension을 없애줌

### Unsqueeze
- 원하는 dimension에 1을 넣어줌
- parameter로 dimension을 꼭 넣어줘야함

### Concatenate
- torch.cat()

### Stacking
- concatenate를 조금 더 편리하게 이용
- torch.stack()